name: app_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  google_maps_flutter: ^2.12.1
  location: ^5.0.3
  permission_handler: ^11.4.0
  geolocator: ^11.1.0
  geocoding: ^2.2.2
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.9
  provider: ^6.0.0
  image_picker: ^1.0.4
  firebase_storage: ^11.7.7
  sensors_plus: ^4.0.2
  firebase_app_check: ^0.2.2+7
  flutter_screenutil: ^5.9.0
  url_launcher: ^6.2.5
  firebase_database: ^10.5.7
  http: ^1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/img/now_position.png
    - assets/img/runner_background.png
    - assets/img/runner_home.png
    - assets/data/서울특별시.json
    - assets/data/부산광역시.json
    - assets/data/대구광역시.json
    - assets/data/인천광역시.json
    - assets/data/광주광역시.json
    - assets/data/대전광역시.json
    - assets/data/울산광역시.json
    - assets/data/세종특별자치시.json
    - assets/data/경기도.json
    - assets/data/강원특별자치도.json
    - assets/data/충청북도.json
    - assets/data/충청남도.json
    - assets/data/전북특별자치도.json
    - assets/data/전라남도.json
    - assets/data/경상북도.json
    - assets/data/경상남도.json
    - assets/data/제주특별자치도.json
    - assets/data/english_word_list.json
    - assets/data/korean_word_list.json
    