enum TagCategory {
  location,    // 지역
  exercise,    // 운동환경
  surrounding, // 주변환경
  etc         // 기타
}

class Tag {
  final String name;
  final TagCategory category;
  final String? parentRegion;  // 상위 지역 (지역 카테고리에서만 사용)

  const Tag({
    required this.name,
    required this.category,
    this.parentRegion,
  });
}

// 샘플 태그 데이터
final List<Tag> sampleTags = [

  // 시/도 지역
  const Tag(name: '서울', category: TagCategory.location),
  const Tag(name: '부산', category: TagCategory.location),
  const Tag(name: '인천', category: TagCategory.location),
  const Tag(name: '대구', category: TagCategory.location),
  const Tag(name: '대전', category: TagCategory.location),
  const Tag(name: '광주', category: TagCategory.location),
  const Tag(name: '울산', category: TagCategory.location),
  const Tag(name: '세종', category: TagCategory.location),
  const Tag(name: '경기', category: TagCategory.location),
  const Tag(name: '강원', category: TagCategory.location),
  const Tag(name: '경북', category: TagCategory.location),
  const Tag(name: '경남', category: TagCategory.location),
  const Tag(name: '충북', category: TagCategory.location),
  const Tag(name: '충남', category: TagCategory.location),
  const Tag(name: '전북', category: TagCategory.location),
  const Tag(name: '전남', category: TagCategory.location),
  const Tag(name: '제주', category: TagCategory.location),

  // 서울 지역
  const Tag(name: '강남구', category: TagCategory.location, parentRegion: '서울'),
  const Tag(name: '강동구', category: TagCategory.location, parentRegion: '서울'),
  const Tag(name: '강북구', category: TagCategory.location, parentRegion: '서울'),
  const Tag(name: '강서구', category: TagCategory.location, parentRegion: '서울'),
  const Tag(name: '관악구', category: TagCategory.location, parentRegion: '서울'),
  const Tag(name: '광진구', category: TagCategory.location, parentRegion: '서울'),
  const Tag(name: '구로구', category: TagCategory.location, parentRegion: '서울'),
  const Tag(name: '금천구', category: TagCategory.location, parentRegion: '서울'),
  const Tag(name: '노원구', category: TagCategory.location, parentRegion: '서울'),
  const Tag(name: '도봉구', category: TagCategory.location, parentRegion: '서울'),
  const Tag(name: '동대문구', category: TagCategory.location, parentRegion: '서울'),
  const Tag(name: '동작구', category: TagCategory.location, parentRegion: '서울'),
  const Tag(name: '마포구', category: TagCategory.location, parentRegion: '서울'),
  const Tag(name: '서대문구', category: TagCategory.location, parentRegion: '서울'),
  const Tag(name: '서초구', category: TagCategory.location, parentRegion: '서울'),
  const Tag(name: '성동구', category: TagCategory.location, parentRegion: '서울'),
  const Tag(name: '성북구', category: TagCategory.location, parentRegion: '서울'),
  const Tag(name: '송파구', category: TagCategory.location, parentRegion: '서울'),
  const Tag(name: '양천구', category: TagCategory.location, parentRegion: '서울'),
  const Tag(name: '영등포구', category: TagCategory.location, parentRegion: '서울'),
  const Tag(name: '용산구', category: TagCategory.location, parentRegion: '서울'),
  const Tag(name: '은평구', category: TagCategory.location, parentRegion: '서울'),
  const Tag(name: '종로구', category: TagCategory.location, parentRegion: '서울'),
  const Tag(name: '중구', category: TagCategory.location, parentRegion: '서울'),
  const Tag(name: '중랑구', category: TagCategory.location, parentRegion: '서울'),

  // 부산 지역
  const Tag(name: '중구', category: TagCategory.location, parentRegion: '부산'),
  const Tag(name: '서구', category: TagCategory.location, parentRegion: '부산'),
  const Tag(name: '동구', category: TagCategory.location, parentRegion: '부산'),
  const Tag(name: '영도구', category: TagCategory.location, parentRegion: '부산'),
  const Tag(name: '부산진구', category: TagCategory.location, parentRegion: '부산'),
  const Tag(name: '동래구', category: TagCategory.location, parentRegion: '부산'),
  const Tag(name: '남구', category: TagCategory.location, parentRegion: '부산'),
  const Tag(name: '북구', category: TagCategory.location, parentRegion: '부산'),
  const Tag(name: '해운대구', category: TagCategory.location, parentRegion: '부산'),
  const Tag(name: '사하구', category: TagCategory.location, parentRegion: '부산'),
  const Tag(name: '금정구', category: TagCategory.location, parentRegion: '부산'),
  const Tag(name: '강서구', category: TagCategory.location, parentRegion: '부산'),
  const Tag(name: '연제구', category: TagCategory.location, parentRegion: '부산'),
  const Tag(name: '수영구', category: TagCategory.location, parentRegion: '부산'),
  const Tag(name: '사상구', category: TagCategory.location, parentRegion: '부산'),
  const Tag(name: '기장군', category: TagCategory.location, parentRegion: '부산'),


  // 인천 지역
  const Tag(name: '중구', category: TagCategory.location, parentRegion: '인천'),
  const Tag(name: '동구', category: TagCategory.location, parentRegion: '인천'),
  const Tag(name: '미추홀구', category: TagCategory.location, parentRegion: '인천'),
  const Tag(name: '연수구', category: TagCategory.location, parentRegion: '인천'),
  const Tag(name: '남동구', category: TagCategory.location, parentRegion: '인천'),
  const Tag(name: '부평구', category: TagCategory.location, parentRegion: '인천'),
  const Tag(name: '계양구', category: TagCategory.location, parentRegion: '인천'),
  const Tag(name: '서구', category: TagCategory.location, parentRegion: '인천'),
  const Tag(name: '강화군', category: TagCategory.location, parentRegion: '인천'),
  const Tag(name: '옹진군', category: TagCategory.location, parentRegion: '인천'),

  // 대구 지역
  const Tag(name: '중구', category: TagCategory.location, parentRegion: '대구'),
  const Tag(name: '동구', category: TagCategory.location, parentRegion: '대구'),
  const Tag(name: '서구', category: TagCategory.location, parentRegion: '대구'),
  const Tag(name: '남구', category: TagCategory.location, parentRegion: '대구'),
  const Tag(name: '북구', category: TagCategory.location, parentRegion: '대구'),
  const Tag(name: '수성구', category: TagCategory.location, parentRegion: '대구'),
  const Tag(name: '달서구', category: TagCategory.location, parentRegion: '대구'),
  const Tag(name: '달성군', category: TagCategory.location, parentRegion: '대구'),

  // 대전 지역
  const Tag(name: '동구', category: TagCategory.location, parentRegion: '대전'),
  const Tag(name: '중구', category: TagCategory.location, parentRegion: '대전'),
  const Tag(name: '서구', category: TagCategory.location, parentRegion: '대전'),
  const Tag(name: '유성구', category: TagCategory.location, parentRegion: '대전'),
  const Tag(name: '대덕구', category: TagCategory.location, parentRegion: '대전'),

  // 광주 지역
  const Tag(name: '동구', category: TagCategory.location, parentRegion: '광주'),
  const Tag(name: '서구', category: TagCategory.location, parentRegion: '광주'),
  const Tag(name: '남구', category: TagCategory.location, parentRegion: '광주'),
  const Tag(name: '북구', category: TagCategory.location, parentRegion: '광주'),
  const Tag(name: '광산구', category: TagCategory.location, parentRegion: '광주'),

  // 울산 지역
  const Tag(name: '중구', category: TagCategory.location, parentRegion: '울산'),
  const Tag(name: '남구', category: TagCategory.location, parentRegion: '울산'),
  const Tag(name: '동구', category: TagCategory.location, parentRegion: '울산'),
  const Tag(name: '북구', category: TagCategory.location, parentRegion: '울산'),
  const Tag(name: '울주군', category: TagCategory.location, parentRegion: '울산'),

  // 세종 지역
  const Tag(name: '세종시', category: TagCategory.location, parentRegion: '세종'),

  // 경기 지역
  const Tag(name: '수원시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '성남시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '의정부시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '안양시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '부천시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '광명시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '평택시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '동두천시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '안산시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '고양시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '과천시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '구리시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '남양주시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '오산시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '시흥시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '군포시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '의왕시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '하남시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '용인시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '파주시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '이천시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '안성시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '김포시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '화성시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '광주시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '양주시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '포천시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '여주시', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '연천군', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '가평군', category: TagCategory.location, parentRegion: '경기'),
  const Tag(name: '양평군', category: TagCategory.location, parentRegion: '경기'),

  // 강원 지역
  const Tag(name: '춘천시', category: TagCategory.location, parentRegion: '강원'),
  const Tag(name: '원주시', category: TagCategory.location, parentRegion: '강원'),
  const Tag(name: '강릉시', category: TagCategory.location, parentRegion: '강원'),
  const Tag(name: '동해시', category: TagCategory.location, parentRegion: '강원'),
  const Tag(name: '태백시', category: TagCategory.location, parentRegion: '강원'),
  const Tag(name: '속초시', category: TagCategory.location, parentRegion: '강원'),
  const Tag(name: '삼척시', category: TagCategory.location, parentRegion: '강원'),
  const Tag(name: '홍천군', category: TagCategory.location, parentRegion: '강원'),
  const Tag(name: '횡성군', category: TagCategory.location, parentRegion: '강원'),
  const Tag(name: '영월군', category: TagCategory.location, parentRegion: '강원'),
  const Tag(name: '평창군', category: TagCategory.location, parentRegion: '강원'),
  const Tag(name: '정선군', category: TagCategory.location, parentRegion: '강원'),
  const Tag(name: '철원군', category: TagCategory.location, parentRegion: '강원'),
  const Tag(name: '화천군', category: TagCategory.location, parentRegion: '강원'),
  const Tag(name: '양구군', category: TagCategory.location, parentRegion: '강원'),
  const Tag(name: '인제군', category: TagCategory.location, parentRegion: '강원'),
  const Tag(name: '고성군', category: TagCategory.location, parentRegion: '강원'),
  const Tag(name: '양양군', category: TagCategory.location, parentRegion: '강원'),

  // 경북 지역
  const Tag(name: '포항시', category: TagCategory.location, parentRegion: '경북'),
  const Tag(name: '경주시', category: TagCategory.location, parentRegion: '경북'),
  const Tag(name: '김천시', category: TagCategory.location, parentRegion: '경북'),
  const Tag(name: '안동시', category: TagCategory.location, parentRegion: '경북'),
  const Tag(name: '구미시', category: TagCategory.location, parentRegion: '경북'),
  const Tag(name: '영주시', category: TagCategory.location, parentRegion: '경북'),
  const Tag(name: '영천시', category: TagCategory.location, parentRegion: '경북'),
  const Tag(name: '상주시', category: TagCategory.location, parentRegion: '경북'),
  const Tag(name: '문경시', category: TagCategory.location, parentRegion: '경북'),
  const Tag(name: '경산시', category: TagCategory.location, parentRegion: '경북'),
  const Tag(name: '군위군', category: TagCategory.location, parentRegion: '경북'),
  const Tag(name: '의성군', category: TagCategory.location, parentRegion: '경북'),
  const Tag(name: '청송군', category: TagCategory.location, parentRegion: '경북'),
  const Tag(name: '영양군', category: TagCategory.location, parentRegion: '경북'),
  const Tag(name: '영덕군', category: TagCategory.location, parentRegion: '경북'),
  const Tag(name: '청도군', category: TagCategory.location, parentRegion: '경북'),
  const Tag(name: '고령군', category: TagCategory.location, parentRegion: '경북'),
  const Tag(name: '성주군', category: TagCategory.location, parentRegion: '경북'),
  const Tag(name: '칠곡군', category: TagCategory.location, parentRegion: '경북'),
  const Tag(name: '예천군', category: TagCategory.location, parentRegion: '경북'),
  const Tag(name: '봉화군', category: TagCategory.location, parentRegion: '경북'),
  const Tag(name: '울진군', category: TagCategory.location, parentRegion: '경북'),
  const Tag(name: '울릉군', category: TagCategory.location, parentRegion: '경북'),

  // 경남 지역
  const Tag(name: '창원시', category: TagCategory.location, parentRegion: '경남'),
  const Tag(name: '진주시', category: TagCategory.location, parentRegion: '경남'),
  const Tag(name: '통영시', category: TagCategory.location, parentRegion: '경남'),
  const Tag(name: '사천시', category: TagCategory.location, parentRegion: '경남'),
  const Tag(name: '김해시', category: TagCategory.location, parentRegion: '경남'),
  const Tag(name: '밀양시', category: TagCategory.location, parentRegion: '경남'),
  const Tag(name: '거제시', category: TagCategory.location, parentRegion: '경남'),
  const Tag(name: '양산시', category: TagCategory.location, parentRegion: '경남'),
  const Tag(name: '의령군', category: TagCategory.location, parentRegion: '경남'),
  const Tag(name: '함안군', category: TagCategory.location, parentRegion: '경남'),
  const Tag(name: '창녕군', category: TagCategory.location, parentRegion: '경남'),
  const Tag(name: '고성군', category: TagCategory.location, parentRegion: '경남'),
  const Tag(name: '남해군', category: TagCategory.location, parentRegion: '경남'),
  const Tag(name: '하동군', category: TagCategory.location, parentRegion: '경남'),
  const Tag(name: '산청군', category: TagCategory.location, parentRegion: '경남'),
  const Tag(name: '함양군', category: TagCategory.location, parentRegion: '경남'),
  const Tag(name: '거창군', category: TagCategory.location, parentRegion: '경남'),
  const Tag(name: '합천군', category: TagCategory.location, parentRegion: '경남'),

  // 충북 지역
  const Tag(name: '청주시', category: TagCategory.location, parentRegion: '충북'),
  const Tag(name: '충주시', category: TagCategory.location, parentRegion: '충북'),
  const Tag(name: '제천시', category: TagCategory.location, parentRegion: '충북'),
  const Tag(name: '보은군', category: TagCategory.location, parentRegion: '충북'),
  const Tag(name: '옥천군', category: TagCategory.location, parentRegion: '충북'),
  const Tag(name: '영동군', category: TagCategory.location, parentRegion: '충북'),
  const Tag(name: '증평군', category: TagCategory.location, parentRegion: '충북'),
  const Tag(name: '진천군', category: TagCategory.location, parentRegion: '충북'),
  const Tag(name: '괴산군', category: TagCategory.location, parentRegion: '충북'),
  const Tag(name: '음성군', category: TagCategory.location, parentRegion: '충북'),
  const Tag(name: '단양군', category: TagCategory.location, parentRegion: '충북'),

  // 충남 지역
  const Tag(name: '천안시', category: TagCategory.location, parentRegion: '충남'),
  const Tag(name: '공주시', category: TagCategory.location, parentRegion: '충남'),
  const Tag(name: '보령시', category: TagCategory.location, parentRegion: '충남'),
  const Tag(name: '아산시', category: TagCategory.location, parentRegion: '충남'),
  const Tag(name: '서산시', category: TagCategory.location, parentRegion: '충남'),
  const Tag(name: '논산시', category: TagCategory.location, parentRegion: '충남'),
  const Tag(name: '계룡시', category: TagCategory.location, parentRegion: '충남'),
  const Tag(name: '당진시', category: TagCategory.location, parentRegion: '충남'),
  const Tag(name: '금산군', category: TagCategory.location, parentRegion: '충남'),
  const Tag(name: '부여군', category: TagCategory.location, parentRegion: '충남'),
  const Tag(name: '서천군', category: TagCategory.location, parentRegion: '충남'),
  const Tag(name: '청양군', category: TagCategory.location, parentRegion: '충남'),
  const Tag(name: '홍성군', category: TagCategory.location, parentRegion: '충남'),
  const Tag(name: '예산군', category: TagCategory.location, parentRegion: '충남'),
  const Tag(name: '태안군', category: TagCategory.location, parentRegion: '충남'),

  // 전북 지역
  const Tag(name: '전주시', category: TagCategory.location, parentRegion: '전북'),
  const Tag(name: '군산시', category: TagCategory.location, parentRegion: '전북'),
  const Tag(name: '익산시', category: TagCategory.location, parentRegion: '전북'),
  const Tag(name: '정읍시', category: TagCategory.location, parentRegion: '전북'),
  const Tag(name: '남원시', category: TagCategory.location, parentRegion: '전북'),
  const Tag(name: '김제시', category: TagCategory.location, parentRegion: '전북'),
  const Tag(name: '완주군', category: TagCategory.location, parentRegion: '전북'),
  const Tag(name: '진안군', category: TagCategory.location, parentRegion: '전북'),
  const Tag(name: '무주군', category: TagCategory.location, parentRegion: '전북'),
  const Tag(name: '장수군', category: TagCategory.location, parentRegion: '전북'),
  const Tag(name: '임실군', category: TagCategory.location, parentRegion: '전북'),
  const Tag(name: '순창군', category: TagCategory.location, parentRegion: '전북'),
  const Tag(name: '고창군', category: TagCategory.location, parentRegion: '전북'),
  const Tag(name: '부안군', category: TagCategory.location, parentRegion: '전북'),

  // 전남 지역
  const Tag(name: '목포시', category: TagCategory.location, parentRegion: '전남'),
  const Tag(name: '여수시', category: TagCategory.location, parentRegion: '전남'),
  const Tag(name: '순천시', category: TagCategory.location, parentRegion: '전남'),
  const Tag(name: '나주시', category: TagCategory.location, parentRegion: '전남'),
  const Tag(name: '광양시', category: TagCategory.location, parentRegion: '전남'),
  const Tag(name: '담양군', category: TagCategory.location, parentRegion: '전남'),
  const Tag(name: '곡성군', category: TagCategory.location, parentRegion: '전남'),
  const Tag(name: '구례군', category: TagCategory.location, parentRegion: '전남'),
  const Tag(name: '고흥군', category: TagCategory.location, parentRegion: '전남'),
  const Tag(name: '보성군', category: TagCategory.location, parentRegion: '전남'),
  const Tag(name: '화순군', category: TagCategory.location, parentRegion: '전남'),
  const Tag(name: '장흥군', category: TagCategory.location, parentRegion: '전남'),
  const Tag(name: '강진군', category: TagCategory.location, parentRegion: '전남'),
  const Tag(name: '해남군', category: TagCategory.location, parentRegion: '전남'),
  const Tag(name: '영암군', category: TagCategory.location, parentRegion: '전남'),
  const Tag(name: '무안군', category: TagCategory.location, parentRegion: '전남'),
  const Tag(name: '함평군', category: TagCategory.location, parentRegion: '전남'),
  const Tag(name: '영광군', category: TagCategory.location, parentRegion: '전남'),
  const Tag(name: '장성군', category: TagCategory.location, parentRegion: '전남'),
  const Tag(name: '완도군', category: TagCategory.location, parentRegion: '전남'),
  const Tag(name: '진도군', category: TagCategory.location, parentRegion: '전남'),
  const Tag(name: '신안군', category: TagCategory.location, parentRegion: '전남'),

  // 제주 지역
  const Tag(name: '제주시', category: TagCategory.location, parentRegion: '제주'),
  const Tag(name: '서귀포시', category: TagCategory.location, parentRegion: '제주'),

  // 기존 태그들 유지
  const Tag(name: '트랙', category: TagCategory.exercise),
  const Tag(name: '아스팔트', category: TagCategory.exercise),
  const Tag(name: '보도블럭', category: TagCategory.exercise),
  const Tag(name: '잔디', category: TagCategory.exercise),
  const Tag(name: '자전거도로', category: TagCategory.exercise),
  const Tag(name: '산책로', category: TagCategory.exercise),
  const Tag(name: '등산로', category: TagCategory.exercise),
  const Tag(name: '흙길', category: TagCategory.exercise),
  const Tag(name: '계단', category: TagCategory.exercise),
  const Tag(name: '오르막길', category: TagCategory.exercise),
  const Tag(name: '내리막길', category: TagCategory.exercise),
  const Tag(name: '다리', category: TagCategory.exercise),
  const Tag(name: '호수', category: TagCategory.exercise),
  const Tag(name: '하천', category: TagCategory.exercise),
  const Tag(name: '개울', category: TagCategory.exercise),
  const Tag(name: '강가', category: TagCategory.exercise),
  const Tag(name: '분수', category: TagCategory.exercise),
  const Tag(name: '수목원', category: TagCategory.exercise),
  const Tag(name: '공원', category: TagCategory.exercise),
  const Tag(name: '경기장', category: TagCategory.exercise),
  const Tag(name: '운동장', category: TagCategory.exercise),
  const Tag(name: '학교', category: TagCategory.exercise),
  const Tag(name: '실내', category: TagCategory.exercise),
  const Tag(name: '실외', category: TagCategory.exercise),

  const Tag(name: '화장실', category: TagCategory.surrounding),
  const Tag(name: '식수대', category: TagCategory.surrounding),
  const Tag(name: '카페', category: TagCategory.surrounding),
  const Tag(name: '편의점', category: TagCategory.surrounding),
  const Tag(name: '마트', category: TagCategory.surrounding),
  const Tag(name: '식당', category: TagCategory.surrounding),
  const Tag(name: '주차장', category: TagCategory.surrounding),
  const Tag(name: '노래방', category: TagCategory.surrounding),
  const Tag(name: '놀이터', category: TagCategory.surrounding),
  const Tag(name: '야외운동기구', category: TagCategory.surrounding),
  const Tag(name: '쉼터', category: TagCategory.surrounding),

  const Tag(name: '24시간', category: TagCategory.etc),
  const Tag(name: '무료', category: TagCategory.etc),
  const Tag(name: '데이트추천', category: TagCategory.etc),
  const Tag(name: '포토존', category: TagCategory.etc),
  const Tag(name: '반려동물동반', category: TagCategory.etc),
  const Tag(name: '초보자추천', category: TagCategory.etc),
  const Tag(name: '이벤트행사', category: TagCategory.etc),
]; 